### ISSUE TITLE
Change config for gps service start and end

### ISSUE THREAD

**Issue by alephcero** [EL-BID/UrbanTrips#72]
Chenge config to
```yaml
    service_type_gps: TYPE
    service_type_start_service: 7
    service_type_finish_service: 8
```

Adapt in code in `renombrar_columnas_tablas()`
