### ISSUE TITLE
traigo_zonificacion returns None in matriz_order when no order is specify

### ISSUE THREAD

**Issue by alephcero** [EL-BID/UrbanTrips#99]
`traigo_zonificacion()` reads from `geojson` [here](https://github.com/EL-BID/UrbanTrips/blob/dev/urbantrips/viz/viz.py#L1436-L1439).

When config doesn't specify an order like this:
```yaml
# Zonificaciones
zonificaciones: 
    geo1: "fracciones_cordoba.geojson"                             
    var1: "link"                                                   
    orden1: 
```
var `matriz_order` becomes `none` and `imprimir_matrices_od()` fails when running `imprime_od()` with that `matriz_order`.

It should return an empty string when order is not specified in config
